### ISSUE TITLE
Getting error while running `pnpm build`

### ISSUE THREAD

**Issue by naz3eh** [mkosir/frontend-monorepo-boilerplate#3]
### Description

While running `pnpm build` as well as `pnpm test`, 3 tasks are failing and am getting an error as shown below
<img width="1477" alt="image" src="https://github.com/mkosir/turborepo-boilerplate/assets/56908732/eba9e4f8-c853-4339-a368-92d1568463c7">

### Additional Information

Initially while attempting to push the `initial commit` to github, `pre push` hook threw me the below error to which created a `pnpm-workspace.yaml` file in the root dir and copied the content in it from [here](https://pnpm.io/pnpm-workspace_yaml)
<img width="1469" alt="image" src="https://github.com/mkosir/turborepo-boilerplate/assets/56908732/ad7df8ea-b3ab-4ae5-9841-3ded1a4e53a5">

**Comment by Nazeeh21** [comment]
I tried running `pnpm clean` and re-installed the `node_modules` and it cleared one task successfully but the other 2 were still failing.
<img width="765" alt="image" src="https://github.com/mkosir/turborepo-boilerplate/assets/56908732/31e1fe41-fc7f-4b54-b355-7ec07b12b3e2">

**Comment by mkosir** [comment]
Hey @Nazeeh21, don't know to well how pnpm manages workspaces in monorepos, but I assume there are some differences by reported errors. Can you navigate into each package that reports error (utils-mui, utils-test) and run build from there, to see if succeeds?

**Comment by Nazeeh21** [comment]
Hey @mkosir, sure trying that!

**Comment by Nazeeh21** [comment]
I tried building packages in their respective folders and it said `@emotion/cache` lib was missing. I added that missing package and it did succeed the build but after that another build error popped up in the `ui` package.
<img width="814" alt="image" src="https://github.com/mkosir/turborepo-boilerplate/assets/56908732/cd78b0dd-3bb3-4043-ac4b-da3d2f3ebc81">

**Comment by mkosir** [comment]
In interesting you needed to add `@emotion/cache`. Can you navigate into each package that reports error (ui) and run build from there, to see if succeeds?

**Comment by mkosir** [comment]
It looks like its related to `pnpm`, found [this issue](https://github.com/microsoft/TypeScript/issues/42873#issuecomment-885815290) that seems tightly related to what you are seeing, can you try if any of the posted solutions works for your case?

**Comment by mkosir** [comment]
Closing this issue since inactivity, feel free to reopen it!
